stages:
  - build
  - deploy

gradle-build:
  image: gradle:7.4-jdk17-alpine
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle clean build
  artifacts:
    paths:
      - build/libs/*.jar
  cache:
    key: gradle-cache
    paths:
      - .gradle/caches

heroku-deploy:
  image: docker:stable
  stage: deploy
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login --username=$HEROKU_USER --password=$HEROKU_API_KEY registry.heroku.com
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - docker build --build-arg JAR_FILE=`ls build/libs/*.jar` --tag registry.heroku.com/$HEROKU_APP_NAME/web .
    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
    - ./release-docker-in-heroku.sh $HEROKU_APP_NAME $HEROKU_API_KEY
